// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5t4N2N3RSw59NH9XSNis1IkjLHp4yrb8',
    appId: '1:64197882688:web:82f73d92dfd4cac69ac0a5',
    messagingSenderId: '64197882688',
    projectId: 'afad-app-23',
    authDomain: 'afad-app-23.firebaseapp.com',
    databaseURL:
        'https://afad-app-23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'afad-app-23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-2wD9-gdE0SGRyN1yeN3YT_BwYK5cw0',
    appId: '1:64197882688:android:8082f76a0ab8a1ee9ac0a5',
    messagingSenderId: '64197882688',
    projectId: 'afad-app-23',
    databaseURL:
        'https://afad-app-23-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'afad-app-23.appspot.com',
  );
}
